name: Deploy TeleDrive (dist) to Server via FTP

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: 📦 Install Latest Node Modules in dist/
        run: |
          cd dist
          npm install --omit=dev --no-audit --no-fund
          cd ..

      - name: 🚀 Deploy dist/ Content to Server via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            .env
